// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgDefineFamily.proto

package com.base.pb;

public final class MsgDefineFamily {
  private MsgDefineFamily() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ProtoNetWorkMessage.FamilyRole}
   *
   * <pre>
   *家族职位
   * </pre>
   */
  public enum FamilyRole
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MASTER = 1;</code>
     *
     * <pre>
     *族长
     * </pre>
     */
    MASTER(0, 1),
    /**
     * <code>SUBMASTER = 2;</code>
     *
     * <pre>
     *副族长
     * </pre>
     */
    SUBMASTER(1, 2),
    /**
     * <code>MEMBER = 3;</code>
     *
     * <pre>
     *普通成员
     * </pre>
     */
    MEMBER(2, 3),
    ;

    /**
     * <code>MASTER = 1;</code>
     *
     * <pre>
     *族长
     * </pre>
     */
    public static final int MASTER_VALUE = 1;
    /**
     * <code>SUBMASTER = 2;</code>
     *
     * <pre>
     *副族长
     * </pre>
     */
    public static final int SUBMASTER_VALUE = 2;
    /**
     * <code>MEMBER = 3;</code>
     *
     * <pre>
     *普通成员
     * </pre>
     */
    public static final int MEMBER_VALUE = 3;


    public final int getNumber() { return value; }

    public static FamilyRole valueOf(int value) {
      switch (value) {
        case 1: return MASTER;
        case 2: return SUBMASTER;
        case 3: return MEMBER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FamilyRole>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FamilyRole>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FamilyRole>() {
            public FamilyRole findValueByNumber(int number) {
              return FamilyRole.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineFamily.getDescriptor().getEnumTypes().get(0);
    }

    private static final FamilyRole[] VALUES = values();

    public static FamilyRole valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FamilyRole(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.FamilyRole)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.FamilyPrerogative}
   *
   * <pre>
   *家族特权
   * </pre>
   */
  public enum FamilyPrerogative
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DRAW = 1;</code>
     *
     * <pre>
     *抽奖
     * </pre>
     */
    DRAW(0, 1),
    /**
     * <code>ONLINEFEED = 2;</code>
     *
     * <pre>
     *喂养神兽
     * </pre>
     */
    ONLINEFEED(1, 2),
    /**
     * <code>FAMILYWAR = 3;</code>
     *
     * <pre>
     *家族战
     * </pre>
     */
    FAMILYWAR(2, 3),
    /**
     * <code>EXCHANGE = 4;</code>
     *
     * <pre>
     *兑换
     * </pre>
     */
    EXCHANGE(3, 4),
    /**
     * <code>FAMILYDECLAREWAR = 5;</code>
     *
     * <pre>
     *家族宣战
     * </pre>
     */
    FAMILYDECLAREWAR(4, 5),
    /**
     * <code>ONLINEBLESS = 6;</code>
     *
     * <pre>
     *神兽赐福
     * </pre>
     */
    ONLINEBLESS(5, 6),
    ;

    /**
     * <code>DRAW = 1;</code>
     *
     * <pre>
     *抽奖
     * </pre>
     */
    public static final int DRAW_VALUE = 1;
    /**
     * <code>ONLINEFEED = 2;</code>
     *
     * <pre>
     *喂养神兽
     * </pre>
     */
    public static final int ONLINEFEED_VALUE = 2;
    /**
     * <code>FAMILYWAR = 3;</code>
     *
     * <pre>
     *家族战
     * </pre>
     */
    public static final int FAMILYWAR_VALUE = 3;
    /**
     * <code>EXCHANGE = 4;</code>
     *
     * <pre>
     *兑换
     * </pre>
     */
    public static final int EXCHANGE_VALUE = 4;
    /**
     * <code>FAMILYDECLAREWAR = 5;</code>
     *
     * <pre>
     *家族宣战
     * </pre>
     */
    public static final int FAMILYDECLAREWAR_VALUE = 5;
    /**
     * <code>ONLINEBLESS = 6;</code>
     *
     * <pre>
     *神兽赐福
     * </pre>
     */
    public static final int ONLINEBLESS_VALUE = 6;


    public final int getNumber() { return value; }

    public static FamilyPrerogative valueOf(int value) {
      switch (value) {
        case 1: return DRAW;
        case 2: return ONLINEFEED;
        case 3: return FAMILYWAR;
        case 4: return EXCHANGE;
        case 5: return FAMILYDECLAREWAR;
        case 6: return ONLINEBLESS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FamilyPrerogative>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FamilyPrerogative>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FamilyPrerogative>() {
            public FamilyPrerogative findValueByNumber(int number) {
              return FamilyPrerogative.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineFamily.getDescriptor().getEnumTypes().get(1);
    }

    private static final FamilyPrerogative[] VALUES = values();

    public static FamilyPrerogative valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FamilyPrerogative(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.FamilyPrerogative)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.FamilyRights}
   *
   * <pre>
   *家族权力
   * </pre>
   */
  public enum FamilyRights
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRANSFER_SHAIKH = 1;</code>
     *
     * <pre>
     *移交族长职位
     * </pre>
     */
    TRANSFER_SHAIKH(0, 1),
    /**
     * <code>KICK_MEMBER = 2;</code>
     *
     * <pre>
     *踢出家族成员
     * </pre>
     */
    KICK_MEMBER(1, 2),
    /**
     * <code>DISPOSE_APPLYLIST = 3;</code>
     *
     * <pre>
     *处理申请名单
     * </pre>
     */
    DISPOSE_APPLYLIST(2, 3),
    /**
     * <code>APPOINT_VICE_SHAIKH = 4;</code>
     *
     * <pre>
     *任命副族长
     * </pre>
     */
    APPOINT_VICE_SHAIKH(3, 4),
    /**
     * <code>DECLARE_WAR = 5;</code>
     *
     * <pre>
     *家族宣战
     * </pre>
     */
    DECLARE_WAR(4, 5),
    /**
     * <code>EDIT_NOTICE = 6;</code>
     *
     * <pre>
     *家族公告修改
     * </pre>
     */
    EDIT_NOTICE(5, 6),
    /**
     * <code>INVITE = 7;</code>
     *
     * <pre>
     *邀请加入
     * </pre>
     */
    INVITE(6, 7),
    ;

    /**
     * <code>TRANSFER_SHAIKH = 1;</code>
     *
     * <pre>
     *移交族长职位
     * </pre>
     */
    public static final int TRANSFER_SHAIKH_VALUE = 1;
    /**
     * <code>KICK_MEMBER = 2;</code>
     *
     * <pre>
     *踢出家族成员
     * </pre>
     */
    public static final int KICK_MEMBER_VALUE = 2;
    /**
     * <code>DISPOSE_APPLYLIST = 3;</code>
     *
     * <pre>
     *处理申请名单
     * </pre>
     */
    public static final int DISPOSE_APPLYLIST_VALUE = 3;
    /**
     * <code>APPOINT_VICE_SHAIKH = 4;</code>
     *
     * <pre>
     *任命副族长
     * </pre>
     */
    public static final int APPOINT_VICE_SHAIKH_VALUE = 4;
    /**
     * <code>DECLARE_WAR = 5;</code>
     *
     * <pre>
     *家族宣战
     * </pre>
     */
    public static final int DECLARE_WAR_VALUE = 5;
    /**
     * <code>EDIT_NOTICE = 6;</code>
     *
     * <pre>
     *家族公告修改
     * </pre>
     */
    public static final int EDIT_NOTICE_VALUE = 6;
    /**
     * <code>INVITE = 7;</code>
     *
     * <pre>
     *邀请加入
     * </pre>
     */
    public static final int INVITE_VALUE = 7;


    public final int getNumber() { return value; }

    public static FamilyRights valueOf(int value) {
      switch (value) {
        case 1: return TRANSFER_SHAIKH;
        case 2: return KICK_MEMBER;
        case 3: return DISPOSE_APPLYLIST;
        case 4: return APPOINT_VICE_SHAIKH;
        case 5: return DECLARE_WAR;
        case 6: return EDIT_NOTICE;
        case 7: return INVITE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FamilyRights>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FamilyRights>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FamilyRights>() {
            public FamilyRights findValueByNumber(int number) {
              return FamilyRights.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineFamily.getDescriptor().getEnumTypes().get(2);
    }

    private static final FamilyRights[] VALUES = values();

    public static FamilyRights valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FamilyRights(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.FamilyRights)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025MsgDefineFamily.proto\022\023ProtoNetWorkMes" +
      "sage*3\n\nFamilyRole\022\n\n\006MASTER\020\001\022\r\n\tSUBMAS" +
      "TER\020\002\022\n\n\006MEMBER\020\003*q\n\021FamilyPrerogative\022\010" +
      "\n\004DRAW\020\001\022\016\n\nONLINEFEED\020\002\022\r\n\tFAMILYWAR\020\003\022" +
      "\014\n\010EXCHANGE\020\004\022\024\n\020FAMILYDECLAREWAR\020\005\022\017\n\013O" +
      "NLINEBLESS\020\006*\222\001\n\014FamilyRights\022\023\n\017TRANSFE" +
      "R_SHAIKH\020\001\022\017\n\013KICK_MEMBER\020\002\022\025\n\021DISPOSE_A" +
      "PPLYLIST\020\003\022\027\n\023APPOINT_VICE_SHAIKH\020\004\022\017\n\013D" +
      "ECLARE_WAR\020\005\022\017\n\013EDIT_NOTICE\020\006\022\n\n\006INVITE\020" +
      "\007B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
