// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgDefineRole.proto

package com.base.pb;

public final class MsgDefineRole {
  private MsgDefineRole() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ProtoNetWorkMessage.SpecialID}
   *
   * <pre>
   *特殊id定义
   * </pre>
   */
  public enum SpecialID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SP_GOLD = 1;</code>
     *
     * <pre>
     *金币常量
     * </pre>
     */
    SP_GOLD(0, 1),
    /**
     * <code>SP_SYCEE = 2;</code>
     *
     * <pre>
     *元宝常量
     * </pre>
     */
    SP_SYCEE(1, 2),
    /**
     * <code>SP_EXP = 3;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    SP_EXP(2, 3),
    /**
     * <code>SP_ENERGY = 4;</code>
     *
     * <pre>
     *体力值
     * </pre>
     */
    SP_ENERGY(3, 4),
    ;

    /**
     * <code>SP_GOLD = 1;</code>
     *
     * <pre>
     *金币常量
     * </pre>
     */
    public static final int SP_GOLD_VALUE = 1;
    /**
     * <code>SP_SYCEE = 2;</code>
     *
     * <pre>
     *元宝常量
     * </pre>
     */
    public static final int SP_SYCEE_VALUE = 2;
    /**
     * <code>SP_EXP = 3;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    public static final int SP_EXP_VALUE = 3;
    /**
     * <code>SP_ENERGY = 4;</code>
     *
     * <pre>
     *体力值
     * </pre>
     */
    public static final int SP_ENERGY_VALUE = 4;


    public final int getNumber() { return value; }

    public static SpecialID valueOf(int value) {
      switch (value) {
        case 1: return SP_GOLD;
        case 2: return SP_SYCEE;
        case 3: return SP_EXP;
        case 4: return SP_ENERGY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SpecialID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SpecialID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SpecialID>() {
            public SpecialID findValueByNumber(int number) {
              return SpecialID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(0);
    }

    private static final SpecialID[] VALUES = values();

    public static SpecialID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SpecialID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.SpecialID)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.ConditionType}
   *
   * <pre>
   *条件类型定义
   * </pre>
   */
  public enum ConditionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CON_LEVEL = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    CON_LEVEL(0, 1),
    /**
     * <code>CON_GOLD = 2;</code>
     *
     * <pre>
     *拥有金币
     * </pre>
     */
    CON_GOLD(1, 2),
    /**
     * <code>CON_DGOLD = 3;</code>
     *
     * <pre>
     *扣除金币
     * </pre>
     */
    CON_DGOLD(2, 3),
    /**
     * <code>CON_SYCEE = 4;</code>
     *
     * <pre>
     *拥有元宝
     * </pre>
     */
    CON_SYCEE(3, 4),
    /**
     * <code>CON_DSYCEE = 5;</code>
     *
     * <pre>
     *扣除元宝
     * </pre>
     */
    CON_DSYCEE(4, 5),
    ;

    /**
     * <code>CON_LEVEL = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public static final int CON_LEVEL_VALUE = 1;
    /**
     * <code>CON_GOLD = 2;</code>
     *
     * <pre>
     *拥有金币
     * </pre>
     */
    public static final int CON_GOLD_VALUE = 2;
    /**
     * <code>CON_DGOLD = 3;</code>
     *
     * <pre>
     *扣除金币
     * </pre>
     */
    public static final int CON_DGOLD_VALUE = 3;
    /**
     * <code>CON_SYCEE = 4;</code>
     *
     * <pre>
     *拥有元宝
     * </pre>
     */
    public static final int CON_SYCEE_VALUE = 4;
    /**
     * <code>CON_DSYCEE = 5;</code>
     *
     * <pre>
     *扣除元宝
     * </pre>
     */
    public static final int CON_DSYCEE_VALUE = 5;


    public final int getNumber() { return value; }

    public static ConditionType valueOf(int value) {
      switch (value) {
        case 1: return CON_LEVEL;
        case 2: return CON_GOLD;
        case 3: return CON_DGOLD;
        case 4: return CON_SYCEE;
        case 5: return CON_DSYCEE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConditionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ConditionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConditionType>() {
            public ConditionType findValueByNumber(int number) {
              return ConditionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(1);
    }

    private static final ConditionType[] VALUES = values();

    public static ConditionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ConditionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.ConditionType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.Career}
   *
   * <pre>
   *职业定义
   * </pre>
   */
  public enum Career
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOCAREER = 1;</code>
     *
     * <pre>
     *无职业限制
     * </pre>
     */
    NOCAREER(0, 1),
    /**
     * <code>CA_CHAKRAM = 2;</code>
     *
     * <pre>
     *飞羽(环刃)
     * </pre>
     */
    CA_CHAKRAM(1, 2),
    /**
     * <code>CA_SWORD = 3;</code>
     *
     * <pre>
     *日月盟（剑）
     * </pre>
     */
    CA_SWORD(2, 3),
    /**
     * <code>CA_FEATHERFAN = 4;</code>
     *
     * <pre>
     *龙门观（扇）
     * </pre>
     */
    CA_FEATHERFAN(3, 4),
    /**
     * <code>CA_GEAR = 5;</code>
     *
     * <pre>
     *雷家堡（机关）
     * </pre>
     */
    CA_GEAR(4, 5),
    ;

    /**
     * <code>NOCAREER = 1;</code>
     *
     * <pre>
     *无职业限制
     * </pre>
     */
    public static final int NOCAREER_VALUE = 1;
    /**
     * <code>CA_CHAKRAM = 2;</code>
     *
     * <pre>
     *飞羽(环刃)
     * </pre>
     */
    public static final int CA_CHAKRAM_VALUE = 2;
    /**
     * <code>CA_SWORD = 3;</code>
     *
     * <pre>
     *日月盟（剑）
     * </pre>
     */
    public static final int CA_SWORD_VALUE = 3;
    /**
     * <code>CA_FEATHERFAN = 4;</code>
     *
     * <pre>
     *龙门观（扇）
     * </pre>
     */
    public static final int CA_FEATHERFAN_VALUE = 4;
    /**
     * <code>CA_GEAR = 5;</code>
     *
     * <pre>
     *雷家堡（机关）
     * </pre>
     */
    public static final int CA_GEAR_VALUE = 5;


    public final int getNumber() { return value; }

    public static Career valueOf(int value) {
      switch (value) {
        case 1: return NOCAREER;
        case 2: return CA_CHAKRAM;
        case 3: return CA_SWORD;
        case 4: return CA_FEATHERFAN;
        case 5: return CA_GEAR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Career>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Career>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Career>() {
            public Career findValueByNumber(int number) {
              return Career.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(2);
    }

    private static final Career[] VALUES = values();

    public static Career valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Career(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.Career)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.Property}
   *
   * <pre>
   *角色属性定义
   * </pre>
   */
  public enum Property
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PR_HP = 1;</code>
     *
     * <pre>
     * 一级属性
     * </pre>
     */
    PR_HP(0, 1),
    /**
     * <code>PR_HPMAX = 2;</code>
     *
     * <pre>
     *血量上限
     * </pre>
     */
    PR_HPMAX(1, 2),
    /**
     * <code>PR_FURY = 3;</code>
     *
     * <pre>
     *怒气
     * </pre>
     */
    PR_FURY(2, 3),
    /**
     * <code>PR_PHYSICALATT = 4;</code>
     *
     * <pre>
     *物理攻击力
     * </pre>
     */
    PR_PHYSICALATT(3, 4),
    /**
     * <code>PR_PHYSICALDEF = 5;</code>
     *
     * <pre>
     *物理防御力
     * </pre>
     */
    PR_PHYSICALDEF(4, 5),
    /**
     * <code>PR_EXP = 6;</code>
     *
     * <pre>
     *当前经验
     * </pre>
     */
    PR_EXP(5, 6),
    /**
     * <code>PR_EXP_MAX = 7;</code>
     *
     * <pre>
     *升级经验
     * </pre>
     */
    PR_EXP_MAX(6, 7),
    /**
     * <code>PR_MAGICATT = 8;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    PR_MAGICATT(7, 8),
    /**
     * <code>PR_MAGICDEF = 9;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    PR_MAGICDEF(8, 9),
    /**
     * <code>PR_SUNDER = 10;</code>
     *
     * <pre>
     *破击
     * </pre>
     */
    PR_SUNDER(9, 10),
    /**
     * <code>PR_SUNDERDEF = 11;</code>
     *
     * <pre>
     *抵抗值
     * </pre>
     */
    PR_SUNDERDEF(10, 11),
    /**
     * <code>PR_CRIT = 12;</code>
     *
     * <pre>
     *暴击
     * </pre>
     */
    PR_CRIT(11, 12),
    /**
     * <code>PR_CRITDEF = 13;</code>
     *
     * <pre>
     *韧性值
     * </pre>
     */
    PR_CRITDEF(12, 13),
    /**
     * <code>PR_DAMAGE_RATIO = 14;</code>
     *
     * <pre>
     *伤害系数
     * </pre>
     */
    PR_DAMAGE_RATIO(13, 14),
    /**
     * <code>PR_HPREGEN = 15;</code>
     *
     * <pre>
     *二级属性
     * </pre>
     */
    PR_HPREGEN(14, 15),
    /**
     * <code>PR_SUNDERPCT = 16;</code>
     *
     * <pre>
     *破击百分比
     * </pre>
     */
    PR_SUNDERPCT(15, 16),
    /**
     * <code>PR_SUNDERDEFPCT = 17;</code>
     *
     * <pre>
     *抵抗百分比
     * </pre>
     */
    PR_SUNDERDEFPCT(16, 17),
    /**
     * <code>PR_CRITPCT = 18;</code>
     *
     * <pre>
     *暴击百分比
     * </pre>
     */
    PR_CRITPCT(17, 18),
    /**
     * <code>PR_CRITDEFPCT = 19;</code>
     *
     * <pre>
     *韧性百分比
     * </pre>
     */
    PR_CRITDEFPCT(18, 19),
    /**
     * <code>PR_PHYSICALATTPCT = 20;</code>
     *
     * <pre>
     *物伤百分比
     * </pre>
     */
    PR_PHYSICALATTPCT(19, 20),
    /**
     * <code>PR_PHYSICALIMMUNEPCT = 21;</code>
     *
     * <pre>
     *物免百分比
     * </pre>
     */
    PR_PHYSICALIMMUNEPCT(20, 21),
    /**
     * <code>PR_MAGICATTPCT = 22;</code>
     *
     * <pre>
     *魔伤百分比
     * </pre>
     */
    PR_MAGICATTPCT(21, 22),
    /**
     * <code>PR_MAGICIMMUNEPCT = 23;</code>
     *
     * <pre>
     *魔免百分比
     * </pre>
     */
    PR_MAGICIMMUNEPCT(22, 23),
    /**
     * <code>PR_SUNDERDEFIMMUNEPCT = 24;</code>
     *
     * <pre>
     *抵抗免伤百分比
     * </pre>
     */
    PR_SUNDERDEFIMMUNEPCT(23, 24),
    /**
     * <code>PR_CRITATTPCT = 25;</code>
     *
     * <pre>
     *暴伤百分比
     * </pre>
     */
    PR_CRITATTPCT(24, 25),
    /**
     * <code>PR_RUNSPEED = 26;</code>
     *
     * <pre>
     *奔跑速度
     * </pre>
     */
    PR_RUNSPEED(25, 26),
    /**
     * <code>PR_SPEEDA = 27;</code>
     *
     * <pre>
     *移速A
     * </pre>
     */
    PR_SPEEDA(26, 27),
    /**
     * <code>PR_SPEEDB = 28;</code>
     *
     * <pre>
     *移速B
     * </pre>
     */
    PR_SPEEDB(27, 28),
    /**
     * <code>PR_NAME = 40;</code>
     *
     * <pre>
     *额外属性，用于服务器之间传递数据
     * </pre>
     */
    PR_NAME(28, 40),
    /**
     * <code>PR_LEVEL = 41;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    PR_LEVEL(29, 41),
    /**
     * <code>PR_CAREER = 42;</code>
     *
     * <pre>
     *职业
     * </pre>
     */
    PR_CAREER(30, 42),
    /**
     * <code>PR_ARMOR = 43;</code>
     *
     * <pre>
     *护甲
     * </pre>
     */
    PR_ARMOR(31, 43),
    /**
     * <code>PR_WEAPON = 44;</code>
     *
     * <pre>
     *武器
     * </pre>
     */
    PR_WEAPON(32, 44),
    /**
     * <code>PR_ITEM = 45;</code>
     *
     * <pre>
     *道具
     * </pre>
     */
    PR_ITEM(33, 45),
    ;

    /**
     * <code>PR_HP = 1;</code>
     *
     * <pre>
     * 一级属性
     * </pre>
     */
    public static final int PR_HP_VALUE = 1;
    /**
     * <code>PR_HPMAX = 2;</code>
     *
     * <pre>
     *血量上限
     * </pre>
     */
    public static final int PR_HPMAX_VALUE = 2;
    /**
     * <code>PR_FURY = 3;</code>
     *
     * <pre>
     *怒气
     * </pre>
     */
    public static final int PR_FURY_VALUE = 3;
    /**
     * <code>PR_PHYSICALATT = 4;</code>
     *
     * <pre>
     *物理攻击力
     * </pre>
     */
    public static final int PR_PHYSICALATT_VALUE = 4;
    /**
     * <code>PR_PHYSICALDEF = 5;</code>
     *
     * <pre>
     *物理防御力
     * </pre>
     */
    public static final int PR_PHYSICALDEF_VALUE = 5;
    /**
     * <code>PR_EXP = 6;</code>
     *
     * <pre>
     *当前经验
     * </pre>
     */
    public static final int PR_EXP_VALUE = 6;
    /**
     * <code>PR_EXP_MAX = 7;</code>
     *
     * <pre>
     *升级经验
     * </pre>
     */
    public static final int PR_EXP_MAX_VALUE = 7;
    /**
     * <code>PR_MAGICATT = 8;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    public static final int PR_MAGICATT_VALUE = 8;
    /**
     * <code>PR_MAGICDEF = 9;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    public static final int PR_MAGICDEF_VALUE = 9;
    /**
     * <code>PR_SUNDER = 10;</code>
     *
     * <pre>
     *破击
     * </pre>
     */
    public static final int PR_SUNDER_VALUE = 10;
    /**
     * <code>PR_SUNDERDEF = 11;</code>
     *
     * <pre>
     *抵抗值
     * </pre>
     */
    public static final int PR_SUNDERDEF_VALUE = 11;
    /**
     * <code>PR_CRIT = 12;</code>
     *
     * <pre>
     *暴击
     * </pre>
     */
    public static final int PR_CRIT_VALUE = 12;
    /**
     * <code>PR_CRITDEF = 13;</code>
     *
     * <pre>
     *韧性值
     * </pre>
     */
    public static final int PR_CRITDEF_VALUE = 13;
    /**
     * <code>PR_DAMAGE_RATIO = 14;</code>
     *
     * <pre>
     *伤害系数
     * </pre>
     */
    public static final int PR_DAMAGE_RATIO_VALUE = 14;
    /**
     * <code>PR_HPREGEN = 15;</code>
     *
     * <pre>
     *二级属性
     * </pre>
     */
    public static final int PR_HPREGEN_VALUE = 15;
    /**
     * <code>PR_SUNDERPCT = 16;</code>
     *
     * <pre>
     *破击百分比
     * </pre>
     */
    public static final int PR_SUNDERPCT_VALUE = 16;
    /**
     * <code>PR_SUNDERDEFPCT = 17;</code>
     *
     * <pre>
     *抵抗百分比
     * </pre>
     */
    public static final int PR_SUNDERDEFPCT_VALUE = 17;
    /**
     * <code>PR_CRITPCT = 18;</code>
     *
     * <pre>
     *暴击百分比
     * </pre>
     */
    public static final int PR_CRITPCT_VALUE = 18;
    /**
     * <code>PR_CRITDEFPCT = 19;</code>
     *
     * <pre>
     *韧性百分比
     * </pre>
     */
    public static final int PR_CRITDEFPCT_VALUE = 19;
    /**
     * <code>PR_PHYSICALATTPCT = 20;</code>
     *
     * <pre>
     *物伤百分比
     * </pre>
     */
    public static final int PR_PHYSICALATTPCT_VALUE = 20;
    /**
     * <code>PR_PHYSICALIMMUNEPCT = 21;</code>
     *
     * <pre>
     *物免百分比
     * </pre>
     */
    public static final int PR_PHYSICALIMMUNEPCT_VALUE = 21;
    /**
     * <code>PR_MAGICATTPCT = 22;</code>
     *
     * <pre>
     *魔伤百分比
     * </pre>
     */
    public static final int PR_MAGICATTPCT_VALUE = 22;
    /**
     * <code>PR_MAGICIMMUNEPCT = 23;</code>
     *
     * <pre>
     *魔免百分比
     * </pre>
     */
    public static final int PR_MAGICIMMUNEPCT_VALUE = 23;
    /**
     * <code>PR_SUNDERDEFIMMUNEPCT = 24;</code>
     *
     * <pre>
     *抵抗免伤百分比
     * </pre>
     */
    public static final int PR_SUNDERDEFIMMUNEPCT_VALUE = 24;
    /**
     * <code>PR_CRITATTPCT = 25;</code>
     *
     * <pre>
     *暴伤百分比
     * </pre>
     */
    public static final int PR_CRITATTPCT_VALUE = 25;
    /**
     * <code>PR_RUNSPEED = 26;</code>
     *
     * <pre>
     *奔跑速度
     * </pre>
     */
    public static final int PR_RUNSPEED_VALUE = 26;
    /**
     * <code>PR_SPEEDA = 27;</code>
     *
     * <pre>
     *移速A
     * </pre>
     */
    public static final int PR_SPEEDA_VALUE = 27;
    /**
     * <code>PR_SPEEDB = 28;</code>
     *
     * <pre>
     *移速B
     * </pre>
     */
    public static final int PR_SPEEDB_VALUE = 28;
    /**
     * <code>PR_NAME = 40;</code>
     *
     * <pre>
     *额外属性，用于服务器之间传递数据
     * </pre>
     */
    public static final int PR_NAME_VALUE = 40;
    /**
     * <code>PR_LEVEL = 41;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public static final int PR_LEVEL_VALUE = 41;
    /**
     * <code>PR_CAREER = 42;</code>
     *
     * <pre>
     *职业
     * </pre>
     */
    public static final int PR_CAREER_VALUE = 42;
    /**
     * <code>PR_ARMOR = 43;</code>
     *
     * <pre>
     *护甲
     * </pre>
     */
    public static final int PR_ARMOR_VALUE = 43;
    /**
     * <code>PR_WEAPON = 44;</code>
     *
     * <pre>
     *武器
     * </pre>
     */
    public static final int PR_WEAPON_VALUE = 44;
    /**
     * <code>PR_ITEM = 45;</code>
     *
     * <pre>
     *道具
     * </pre>
     */
    public static final int PR_ITEM_VALUE = 45;


    public final int getNumber() { return value; }

    public static Property valueOf(int value) {
      switch (value) {
        case 1: return PR_HP;
        case 2: return PR_HPMAX;
        case 3: return PR_FURY;
        case 4: return PR_PHYSICALATT;
        case 5: return PR_PHYSICALDEF;
        case 6: return PR_EXP;
        case 7: return PR_EXP_MAX;
        case 8: return PR_MAGICATT;
        case 9: return PR_MAGICDEF;
        case 10: return PR_SUNDER;
        case 11: return PR_SUNDERDEF;
        case 12: return PR_CRIT;
        case 13: return PR_CRITDEF;
        case 14: return PR_DAMAGE_RATIO;
        case 15: return PR_HPREGEN;
        case 16: return PR_SUNDERPCT;
        case 17: return PR_SUNDERDEFPCT;
        case 18: return PR_CRITPCT;
        case 19: return PR_CRITDEFPCT;
        case 20: return PR_PHYSICALATTPCT;
        case 21: return PR_PHYSICALIMMUNEPCT;
        case 22: return PR_MAGICATTPCT;
        case 23: return PR_MAGICIMMUNEPCT;
        case 24: return PR_SUNDERDEFIMMUNEPCT;
        case 25: return PR_CRITATTPCT;
        case 26: return PR_RUNSPEED;
        case 27: return PR_SPEEDA;
        case 28: return PR_SPEEDB;
        case 40: return PR_NAME;
        case 41: return PR_LEVEL;
        case 42: return PR_CAREER;
        case 43: return PR_ARMOR;
        case 44: return PR_WEAPON;
        case 45: return PR_ITEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Property>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Property>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Property>() {
            public Property findValueByNumber(int number) {
              return Property.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(3);
    }

    private static final Property[] VALUES = values();

    public static Property valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Property(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.Property)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.Channel}
   *
   * <pre>
   *聊天频道定义
   * </pre>
   */
  public enum Channel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CH_WORLD_CHAT = 1;</code>
     *
     * <pre>
     *世界频道
     * </pre>
     */
    CH_WORLD_CHAT(0, 1),
    /**
     * <code>CH_FAMILY_CHAT = 2;</code>
     *
     * <pre>
     *家族
     * </pre>
     */
    CH_FAMILY_CHAT(1, 2),
    /**
     * <code>CH_TEAM_CHAT = 3;</code>
     *
     * <pre>
     *组队
     * </pre>
     */
    CH_TEAM_CHAT(2, 3),
    /**
     * <code>CH_PRIVATE_CHAT = 4;</code>
     *
     * <pre>
     *私聊
     * </pre>
     */
    CH_PRIVATE_CHAT(3, 4),
    /**
     * <code>CH_SYSTEM_CHAT = 5;</code>
     *
     * <pre>
     *系统广播
     * </pre>
     */
    CH_SYSTEM_CHAT(4, 5),
    ;

    /**
     * <code>CH_WORLD_CHAT = 1;</code>
     *
     * <pre>
     *世界频道
     * </pre>
     */
    public static final int CH_WORLD_CHAT_VALUE = 1;
    /**
     * <code>CH_FAMILY_CHAT = 2;</code>
     *
     * <pre>
     *家族
     * </pre>
     */
    public static final int CH_FAMILY_CHAT_VALUE = 2;
    /**
     * <code>CH_TEAM_CHAT = 3;</code>
     *
     * <pre>
     *组队
     * </pre>
     */
    public static final int CH_TEAM_CHAT_VALUE = 3;
    /**
     * <code>CH_PRIVATE_CHAT = 4;</code>
     *
     * <pre>
     *私聊
     * </pre>
     */
    public static final int CH_PRIVATE_CHAT_VALUE = 4;
    /**
     * <code>CH_SYSTEM_CHAT = 5;</code>
     *
     * <pre>
     *系统广播
     * </pre>
     */
    public static final int CH_SYSTEM_CHAT_VALUE = 5;


    public final int getNumber() { return value; }

    public static Channel valueOf(int value) {
      switch (value) {
        case 1: return CH_WORLD_CHAT;
        case 2: return CH_FAMILY_CHAT;
        case 3: return CH_TEAM_CHAT;
        case 4: return CH_PRIVATE_CHAT;
        case 5: return CH_SYSTEM_CHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Channel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Channel>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
            public Channel findValueByNumber(int number) {
              return Channel.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(4);
    }

    private static final Channel[] VALUES = values();

    public static Channel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Channel(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.Channel)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.BackType}
   *
   * <pre>
   *物品位置
   * </pre>
   */
  public enum BackType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BACKPACK = 1;</code>
     *
     * <pre>
     *背包
     * </pre>
     */
    BACKPACK(0, 1),
    /**
     * <code>WAREHOUSE = 2;</code>
     *
     * <pre>
     *仓库
     * </pre>
     */
    WAREHOUSE(1, 2),
    /**
     * <code>EQUIPSLOT = 3;</code>
     *
     * <pre>
     *装备槽
     * </pre>
     */
    EQUIPSLOT(2, 3),
    /**
     * <code>GEMBACKPACK = 4;</code>
     *
     * <pre>
     *宝石背包
     * </pre>
     */
    GEMBACKPACK(3, 4),
    /**
     * <code>GEMCOLUMN = 5;</code>
     *
     * <pre>
     *宝石栏
     * </pre>
     */
    GEMCOLUMN(4, 5),
    ;

    /**
     * <code>BACKPACK = 1;</code>
     *
     * <pre>
     *背包
     * </pre>
     */
    public static final int BACKPACK_VALUE = 1;
    /**
     * <code>WAREHOUSE = 2;</code>
     *
     * <pre>
     *仓库
     * </pre>
     */
    public static final int WAREHOUSE_VALUE = 2;
    /**
     * <code>EQUIPSLOT = 3;</code>
     *
     * <pre>
     *装备槽
     * </pre>
     */
    public static final int EQUIPSLOT_VALUE = 3;
    /**
     * <code>GEMBACKPACK = 4;</code>
     *
     * <pre>
     *宝石背包
     * </pre>
     */
    public static final int GEMBACKPACK_VALUE = 4;
    /**
     * <code>GEMCOLUMN = 5;</code>
     *
     * <pre>
     *宝石栏
     * </pre>
     */
    public static final int GEMCOLUMN_VALUE = 5;


    public final int getNumber() { return value; }

    public static BackType valueOf(int value) {
      switch (value) {
        case 1: return BACKPACK;
        case 2: return WAREHOUSE;
        case 3: return EQUIPSLOT;
        case 4: return GEMBACKPACK;
        case 5: return GEMCOLUMN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BackType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BackType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BackType>() {
            public BackType findValueByNumber(int number) {
              return BackType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(5);
    }

    private static final BackType[] VALUES = values();

    public static BackType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BackType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.BackType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.SocialType}
   *
   * <pre>
   *社交类型
   * </pre>
   */
  public enum SocialType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FRIEND = 1;</code>
     *
     * <pre>
     *好友
     * </pre>
     */
    FRIEND(0, 1),
    /**
     * <code>ENEMY = 2;</code>
     *
     * <pre>
     *仇人
     * </pre>
     */
    ENEMY(1, 2),
    ;

    /**
     * <code>FRIEND = 1;</code>
     *
     * <pre>
     *好友
     * </pre>
     */
    public static final int FRIEND_VALUE = 1;
    /**
     * <code>ENEMY = 2;</code>
     *
     * <pre>
     *仇人
     * </pre>
     */
    public static final int ENEMY_VALUE = 2;


    public final int getNumber() { return value; }

    public static SocialType valueOf(int value) {
      switch (value) {
        case 1: return FRIEND;
        case 2: return ENEMY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SocialType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SocialType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SocialType>() {
            public SocialType findValueByNumber(int number) {
              return SocialType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(6);
    }

    private static final SocialType[] VALUES = values();

    public static SocialType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SocialType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.SocialType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.ChestOpenType}
   *
   * <pre>
   *宝箱开启模式
   * </pre>
   */
  public enum ChestOpenType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OPEN_ALL = 1;</code>
     *
     * <pre>
     *全部
     * </pre>
     */
    OPEN_ALL(0, 1),
    /**
     * <code>OPEN_RAND = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    OPEN_RAND(1, 2),
    ;

    /**
     * <code>OPEN_ALL = 1;</code>
     *
     * <pre>
     *全部
     * </pre>
     */
    public static final int OPEN_ALL_VALUE = 1;
    /**
     * <code>OPEN_RAND = 2;</code>
     *
     * <pre>
     *随机
     * </pre>
     */
    public static final int OPEN_RAND_VALUE = 2;


    public final int getNumber() { return value; }

    public static ChestOpenType valueOf(int value) {
      switch (value) {
        case 1: return OPEN_ALL;
        case 2: return OPEN_RAND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChestOpenType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChestOpenType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChestOpenType>() {
            public ChestOpenType findValueByNumber(int number) {
              return ChestOpenType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(7);
    }

    private static final ChestOpenType[] VALUES = values();

    public static ChestOpenType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ChestOpenType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.ChestOpenType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.MailType}
   *
   * <pre>
   *邮件类型
   * </pre>
   */
  public enum MailType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MAIL_SYSTEM = 1;</code>
     *
     * <pre>
     *系统邮件
     * </pre>
     */
    MAIL_SYSTEM(0, 1),
    /**
     * <code>MAIL_ROLE = 2;</code>
     *
     * <pre>
     *玩家个人邮件
     * </pre>
     */
    MAIL_ROLE(1, 2),
    /**
     * <code>MAIL_GM = 3;</code>
     *
     * <pre>
     *GM命令邮件
     * </pre>
     */
    MAIL_GM(2, 3),
    ;

    /**
     * <code>MAIL_SYSTEM = 1;</code>
     *
     * <pre>
     *系统邮件
     * </pre>
     */
    public static final int MAIL_SYSTEM_VALUE = 1;
    /**
     * <code>MAIL_ROLE = 2;</code>
     *
     * <pre>
     *玩家个人邮件
     * </pre>
     */
    public static final int MAIL_ROLE_VALUE = 2;
    /**
     * <code>MAIL_GM = 3;</code>
     *
     * <pre>
     *GM命令邮件
     * </pre>
     */
    public static final int MAIL_GM_VALUE = 3;


    public final int getNumber() { return value; }

    public static MailType valueOf(int value) {
      switch (value) {
        case 1: return MAIL_SYSTEM;
        case 2: return MAIL_ROLE;
        case 3: return MAIL_GM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MailType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MailType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MailType>() {
            public MailType findValueByNumber(int number) {
              return MailType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineRole.getDescriptor().getEnumTypes().get(8);
    }

    private static final MailType[] VALUES = values();

    public static MailType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MailType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.MailType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MsgDefineRole.proto\022\023ProtoNetWorkMessa" +
      "ge*A\n\tSpecialID\022\013\n\007SP_GOLD\020\001\022\014\n\010SP_SYCEE" +
      "\020\002\022\n\n\006SP_EXP\020\003\022\r\n\tSP_ENERGY\020\004*Z\n\rConditi" +
      "onType\022\r\n\tCON_LEVEL\020\001\022\014\n\010CON_GOLD\020\002\022\r\n\tC" +
      "ON_DGOLD\020\003\022\r\n\tCON_SYCEE\020\004\022\016\n\nCON_DSYCEE\020" +
      "\005*T\n\006Career\022\014\n\010NOCAREER\020\001\022\016\n\nCA_CHAKRAM\020" +
      "\002\022\014\n\010CA_SWORD\020\003\022\021\n\rCA_FEATHERFAN\020\004\022\013\n\007CA" +
      "_GEAR\020\005*\320\004\n\010Property\022\t\n\005PR_HP\020\001\022\014\n\010PR_HP" +
      "MAX\020\002\022\013\n\007PR_FURY\020\003\022\022\n\016PR_PHYSICALATT\020\004\022\022" +
      "\n\016PR_PHYSICALDEF\020\005\022\n\n\006PR_EXP\020\006\022\016\n\nPR_EXP",
      "_MAX\020\007\022\017\n\013PR_MAGICATT\020\010\022\017\n\013PR_MAGICDEF\020\t" +
      "\022\r\n\tPR_SUNDER\020\n\022\020\n\014PR_SUNDERDEF\020\013\022\013\n\007PR_" +
      "CRIT\020\014\022\016\n\nPR_CRITDEF\020\r\022\023\n\017PR_DAMAGE_RATI" +
      "O\020\016\022\016\n\nPR_HPREGEN\020\017\022\020\n\014PR_SUNDERPCT\020\020\022\023\n" +
      "\017PR_SUNDERDEFPCT\020\021\022\016\n\nPR_CRITPCT\020\022\022\021\n\rPR" +
      "_CRITDEFPCT\020\023\022\025\n\021PR_PHYSICALATTPCT\020\024\022\030\n\024" +
      "PR_PHYSICALIMMUNEPCT\020\025\022\022\n\016PR_MAGICATTPCT" +
      "\020\026\022\025\n\021PR_MAGICIMMUNEPCT\020\027\022\031\n\025PR_SUNDERDE" +
      "FIMMUNEPCT\020\030\022\021\n\rPR_CRITATTPCT\020\031\022\017\n\013PR_RU" +
      "NSPEED\020\032\022\r\n\tPR_SPEEDA\020\033\022\r\n\tPR_SPEEDB\020\034\022\013",
      "\n\007PR_NAME\020(\022\014\n\010PR_LEVEL\020)\022\r\n\tPR_CAREER\020*" +
      "\022\014\n\010PR_ARMOR\020+\022\r\n\tPR_WEAPON\020,\022\013\n\007PR_ITEM" +
      "\020-*k\n\007Channel\022\021\n\rCH_WORLD_CHAT\020\001\022\022\n\016CH_F" +
      "AMILY_CHAT\020\002\022\020\n\014CH_TEAM_CHAT\020\003\022\023\n\017CH_PRI" +
      "VATE_CHAT\020\004\022\022\n\016CH_SYSTEM_CHAT\020\005*V\n\010BackT" +
      "ype\022\014\n\010BACKPACK\020\001\022\r\n\tWAREHOUSE\020\002\022\r\n\tEQUI" +
      "PSLOT\020\003\022\017\n\013GEMBACKPACK\020\004\022\r\n\tGEMCOLUMN\020\005*" +
      "#\n\nSocialType\022\n\n\006FRIEND\020\001\022\t\n\005ENEMY\020\002*,\n\r" +
      "ChestOpenType\022\014\n\010OPEN_ALL\020\001\022\r\n\tOPEN_RAND" +
      "\020\002*7\n\010MailType\022\017\n\013MAIL_SYSTEM\020\001\022\r\n\tMAIL_",
      "ROLE\020\002\022\013\n\007MAIL_GM\020\003B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
