// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgDefineItem.proto

package com.base.pb;

public final class MsgDefineItem {
  private MsgDefineItem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ProtoNetWorkMessage.ItemType}
   *
   * <pre>
   *道具类型
   * </pre>
   */
  public enum ItemType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONSUME_ITEM = 1;</code>
     *
     * <pre>
     *消耗类道具
     * </pre>
     */
    CONSUME_ITEM(0, 1),
    /**
     * <code>EQUIP_ITEM = 2;</code>
     *
     * <pre>
     *装备道具
     * </pre>
     */
    EQUIP_ITEM(1, 2),
    /**
     * <code>CHEST_ITEM = 3;</code>
     *
     * <pre>
     *宝箱道具
     * </pre>
     */
    CHEST_ITEM(2, 3),
    /**
     * <code>GEM_ITEM = 4;</code>
     *
     * <pre>
     *宝石道具
     * </pre>
     */
    GEM_ITEM(3, 4),
    /**
     * <code>CURRENCY_ITEM = 5;</code>
     *
     * <pre>
     *货币道具
     * </pre>
     */
    CURRENCY_ITEM(4, 5),
    /**
     * <code>MATERIAL_ITEM = 6;</code>
     *
     * <pre>
     *材料
     * </pre>
     */
    MATERIAL_ITEM(5, 6),
    /**
     * <code>BUFFER_ITEM = 7;</code>
     *
     * <pre>
     *buffer类道具
     * </pre>
     */
    BUFFER_ITEM(6, 7),
    /**
     * <code>SKILL_BOOK_ITEM = 8;</code>
     *
     * <pre>
     *技能书道具
     * </pre>
     */
    SKILL_BOOK_ITEM(7, 8),
    /**
     * <code>NOMAL_ITEM = 9;</code>
     *
     * <pre>
     *普通类道具
     * </pre>
     */
    NOMAL_ITEM(8, 9),
    ;

    /**
     * <code>CONSUME_ITEM = 1;</code>
     *
     * <pre>
     *消耗类道具
     * </pre>
     */
    public static final int CONSUME_ITEM_VALUE = 1;
    /**
     * <code>EQUIP_ITEM = 2;</code>
     *
     * <pre>
     *装备道具
     * </pre>
     */
    public static final int EQUIP_ITEM_VALUE = 2;
    /**
     * <code>CHEST_ITEM = 3;</code>
     *
     * <pre>
     *宝箱道具
     * </pre>
     */
    public static final int CHEST_ITEM_VALUE = 3;
    /**
     * <code>GEM_ITEM = 4;</code>
     *
     * <pre>
     *宝石道具
     * </pre>
     */
    public static final int GEM_ITEM_VALUE = 4;
    /**
     * <code>CURRENCY_ITEM = 5;</code>
     *
     * <pre>
     *货币道具
     * </pre>
     */
    public static final int CURRENCY_ITEM_VALUE = 5;
    /**
     * <code>MATERIAL_ITEM = 6;</code>
     *
     * <pre>
     *材料
     * </pre>
     */
    public static final int MATERIAL_ITEM_VALUE = 6;
    /**
     * <code>BUFFER_ITEM = 7;</code>
     *
     * <pre>
     *buffer类道具
     * </pre>
     */
    public static final int BUFFER_ITEM_VALUE = 7;
    /**
     * <code>SKILL_BOOK_ITEM = 8;</code>
     *
     * <pre>
     *技能书道具
     * </pre>
     */
    public static final int SKILL_BOOK_ITEM_VALUE = 8;
    /**
     * <code>NOMAL_ITEM = 9;</code>
     *
     * <pre>
     *普通类道具
     * </pre>
     */
    public static final int NOMAL_ITEM_VALUE = 9;


    public final int getNumber() { return value; }

    public static ItemType valueOf(int value) {
      switch (value) {
        case 1: return CONSUME_ITEM;
        case 2: return EQUIP_ITEM;
        case 3: return CHEST_ITEM;
        case 4: return GEM_ITEM;
        case 5: return CURRENCY_ITEM;
        case 6: return MATERIAL_ITEM;
        case 7: return BUFFER_ITEM;
        case 8: return SKILL_BOOK_ITEM;
        case 9: return NOMAL_ITEM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ItemType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemType>() {
            public ItemType findValueByNumber(int number) {
              return ItemType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineItem.getDescriptor().getEnumTypes().get(0);
    }

    private static final ItemType[] VALUES = values();

    public static ItemType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ItemType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.ItemType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.ItemColor}
   *
   * <pre>
   *装备品质定义
   * </pre>
   */
  public enum ItemColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WHITE = 1;</code>
     *
     * <pre>
     *白色
     * </pre>
     */
    WHITE(0, 1),
    /**
     * <code>GREEN = 2;</code>
     *
     * <pre>
     *绿色
     * </pre>
     */
    GREEN(1, 2),
    /**
     * <code>BLUE = 3;</code>
     *
     * <pre>
     *蓝色
     * </pre>
     */
    BLUE(2, 3),
    /**
     * <code>PURPLE = 4;</code>
     *
     * <pre>
     *紫色
     * </pre>
     */
    PURPLE(3, 4),
    /**
     * <code>GOLDEN = 5;</code>
     *
     * <pre>
     *金色
     * </pre>
     */
    GOLDEN(4, 5),
    /**
     * <code>ORANGE = 6;</code>
     *
     * <pre>
     *橙色
     * </pre>
     */
    ORANGE(5, 6),
    /**
     * <code>RED = 7;</code>
     *
     * <pre>
     *红色
     * </pre>
     */
    RED(6, 7),
    ;

    /**
     * <code>WHITE = 1;</code>
     *
     * <pre>
     *白色
     * </pre>
     */
    public static final int WHITE_VALUE = 1;
    /**
     * <code>GREEN = 2;</code>
     *
     * <pre>
     *绿色
     * </pre>
     */
    public static final int GREEN_VALUE = 2;
    /**
     * <code>BLUE = 3;</code>
     *
     * <pre>
     *蓝色
     * </pre>
     */
    public static final int BLUE_VALUE = 3;
    /**
     * <code>PURPLE = 4;</code>
     *
     * <pre>
     *紫色
     * </pre>
     */
    public static final int PURPLE_VALUE = 4;
    /**
     * <code>GOLDEN = 5;</code>
     *
     * <pre>
     *金色
     * </pre>
     */
    public static final int GOLDEN_VALUE = 5;
    /**
     * <code>ORANGE = 6;</code>
     *
     * <pre>
     *橙色
     * </pre>
     */
    public static final int ORANGE_VALUE = 6;
    /**
     * <code>RED = 7;</code>
     *
     * <pre>
     *红色
     * </pre>
     */
    public static final int RED_VALUE = 7;


    public final int getNumber() { return value; }

    public static ItemColor valueOf(int value) {
      switch (value) {
        case 1: return WHITE;
        case 2: return GREEN;
        case 3: return BLUE;
        case 4: return PURPLE;
        case 5: return GOLDEN;
        case 6: return ORANGE;
        case 7: return RED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ItemColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ItemColor>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ItemColor>() {
            public ItemColor findValueByNumber(int number) {
              return ItemColor.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineItem.getDescriptor().getEnumTypes().get(1);
    }

    private static final ItemColor[] VALUES = values();

    public static ItemColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ItemColor(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.ItemColor)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.ReflectType}
   *
   * <pre>
   *影响类型
   * </pre>
   */
  public enum ReflectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD_HP_ONE_TIME = 1;</code>
     *
     * <pre>
     *一次性提升生命
     * </pre>
     */
    ADD_HP_ONE_TIME(0, 1),
    /**
     * <code>ADD_FURY_ONE_TIME = 2;</code>
     *
     * <pre>
     *一次性提升怒气
     * </pre>
     */
    ADD_FURY_ONE_TIME(1, 2),
    /**
     * <code>ADD_ENERGY_ONE_TIME = 3;</code>
     *
     * <pre>
     *一次性提升体力
     * </pre>
     */
    ADD_ENERGY_ONE_TIME(2, 3),
    /**
     * <code>ADD_GOLD_ONE_TIME = 4;</code>
     *
     * <pre>
     *一次性提升金币数量
     * </pre>
     */
    ADD_GOLD_ONE_TIME(3, 4),
    /**
     * <code>ADD_SYCEE_ONE_TIME = 5;</code>
     *
     * <pre>
     *一次性提升元宝数量
     * </pre>
     */
    ADD_SYCEE_ONE_TIME(4, 5),
    /**
     * <code>ADD_GEM_PIECE_ONE_TIME = 6;</code>
     *
     * <pre>
     *一次性提升宝石碎片数量
     * </pre>
     */
    ADD_GEM_PIECE_ONE_TIME(5, 6),
    /**
     * <code>ADD_ROLE_EXP_ONE_TIME = 7;</code>
     *
     * <pre>
     *一次性提升人物经验
     * </pre>
     */
    ADD_ROLE_EXP_ONE_TIME(6, 7),
    /**
     * <code>ADD_PET_EXP_ONE_TIME = 8;</code>
     *
     * <pre>
     *一次性增加宠物经验
     * </pre>
     */
    ADD_PET_EXP_ONE_TIME(7, 8),
    ;

    /**
     * <code>ADD_HP_ONE_TIME = 1;</code>
     *
     * <pre>
     *一次性提升生命
     * </pre>
     */
    public static final int ADD_HP_ONE_TIME_VALUE = 1;
    /**
     * <code>ADD_FURY_ONE_TIME = 2;</code>
     *
     * <pre>
     *一次性提升怒气
     * </pre>
     */
    public static final int ADD_FURY_ONE_TIME_VALUE = 2;
    /**
     * <code>ADD_ENERGY_ONE_TIME = 3;</code>
     *
     * <pre>
     *一次性提升体力
     * </pre>
     */
    public static final int ADD_ENERGY_ONE_TIME_VALUE = 3;
    /**
     * <code>ADD_GOLD_ONE_TIME = 4;</code>
     *
     * <pre>
     *一次性提升金币数量
     * </pre>
     */
    public static final int ADD_GOLD_ONE_TIME_VALUE = 4;
    /**
     * <code>ADD_SYCEE_ONE_TIME = 5;</code>
     *
     * <pre>
     *一次性提升元宝数量
     * </pre>
     */
    public static final int ADD_SYCEE_ONE_TIME_VALUE = 5;
    /**
     * <code>ADD_GEM_PIECE_ONE_TIME = 6;</code>
     *
     * <pre>
     *一次性提升宝石碎片数量
     * </pre>
     */
    public static final int ADD_GEM_PIECE_ONE_TIME_VALUE = 6;
    /**
     * <code>ADD_ROLE_EXP_ONE_TIME = 7;</code>
     *
     * <pre>
     *一次性提升人物经验
     * </pre>
     */
    public static final int ADD_ROLE_EXP_ONE_TIME_VALUE = 7;
    /**
     * <code>ADD_PET_EXP_ONE_TIME = 8;</code>
     *
     * <pre>
     *一次性增加宠物经验
     * </pre>
     */
    public static final int ADD_PET_EXP_ONE_TIME_VALUE = 8;


    public final int getNumber() { return value; }

    public static ReflectType valueOf(int value) {
      switch (value) {
        case 1: return ADD_HP_ONE_TIME;
        case 2: return ADD_FURY_ONE_TIME;
        case 3: return ADD_ENERGY_ONE_TIME;
        case 4: return ADD_GOLD_ONE_TIME;
        case 5: return ADD_SYCEE_ONE_TIME;
        case 6: return ADD_GEM_PIECE_ONE_TIME;
        case 7: return ADD_ROLE_EXP_ONE_TIME;
        case 8: return ADD_PET_EXP_ONE_TIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReflectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ReflectType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReflectType>() {
            public ReflectType findValueByNumber(int number) {
              return ReflectType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineItem.getDescriptor().getEnumTypes().get(2);
    }

    private static final ReflectType[] VALUES = values();

    public static ReflectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ReflectType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.ReflectType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.Part}
   *
   * <pre>
   *部位
   * </pre>
   */
  public enum Part
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WEAPON_PART = 1;</code>
     *
     * <pre>
     *武器
     * </pre>
     */
    WEAPON_PART(0, 1),
    /**
     * <code>CLOTHES_PART = 2;</code>
     *
     * <pre>
     *衣服
     * </pre>
     */
    CLOTHES_PART(1, 2),
    /**
     * <code>HAND_PART = 3;</code>
     *
     * <pre>
     *护手
     * </pre>
     */
    HAND_PART(2, 3),
    /**
     * <code>HELMET_PART = 4;</code>
     *
     * <pre>
     *头盔
     * </pre>
     */
    HELMET_PART(3, 4),
    /**
     * <code>BELT_PART = 5;</code>
     *
     * <pre>
     *腰带
     * </pre>
     */
    BELT_PART(4, 5),
    /**
     * <code>SHOE_PART = 6;</code>
     *
     * <pre>
     *鞋子
     * </pre>
     */
    SHOE_PART(5, 6),
    /**
     * <code>FASHION = 7;</code>
     *
     * <pre>
     *时装
     * </pre>
     */
    FASHION(6, 7),
    ;

    /**
     * <code>WEAPON_PART = 1;</code>
     *
     * <pre>
     *武器
     * </pre>
     */
    public static final int WEAPON_PART_VALUE = 1;
    /**
     * <code>CLOTHES_PART = 2;</code>
     *
     * <pre>
     *衣服
     * </pre>
     */
    public static final int CLOTHES_PART_VALUE = 2;
    /**
     * <code>HAND_PART = 3;</code>
     *
     * <pre>
     *护手
     * </pre>
     */
    public static final int HAND_PART_VALUE = 3;
    /**
     * <code>HELMET_PART = 4;</code>
     *
     * <pre>
     *头盔
     * </pre>
     */
    public static final int HELMET_PART_VALUE = 4;
    /**
     * <code>BELT_PART = 5;</code>
     *
     * <pre>
     *腰带
     * </pre>
     */
    public static final int BELT_PART_VALUE = 5;
    /**
     * <code>SHOE_PART = 6;</code>
     *
     * <pre>
     *鞋子
     * </pre>
     */
    public static final int SHOE_PART_VALUE = 6;
    /**
     * <code>FASHION = 7;</code>
     *
     * <pre>
     *时装
     * </pre>
     */
    public static final int FASHION_VALUE = 7;


    public final int getNumber() { return value; }

    public static Part valueOf(int value) {
      switch (value) {
        case 1: return WEAPON_PART;
        case 2: return CLOTHES_PART;
        case 3: return HAND_PART;
        case 4: return HELMET_PART;
        case 5: return BELT_PART;
        case 6: return SHOE_PART;
        case 7: return FASHION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Part>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Part>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Part>() {
            public Part findValueByNumber(int number) {
              return Part.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineItem.getDescriptor().getEnumTypes().get(3);
    }

    private static final Part[] VALUES = values();

    public static Part valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Part(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.Part)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.PolishType}
   *
   * <pre>
   *洗练类型
   * </pre>
   */
  public enum PolishType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GOLD_POLISH = 1;</code>
     *
     * <pre>
     *金币洗练
     * </pre>
     */
    GOLD_POLISH(0, 1),
    /**
     * <code>SYCEE_POLISH = 2;</code>
     *
     * <pre>
     *元宝洗练
     * </pre>
     */
    SYCEE_POLISH(1, 2),
    ;

    /**
     * <code>GOLD_POLISH = 1;</code>
     *
     * <pre>
     *金币洗练
     * </pre>
     */
    public static final int GOLD_POLISH_VALUE = 1;
    /**
     * <code>SYCEE_POLISH = 2;</code>
     *
     * <pre>
     *元宝洗练
     * </pre>
     */
    public static final int SYCEE_POLISH_VALUE = 2;


    public final int getNumber() { return value; }

    public static PolishType valueOf(int value) {
      switch (value) {
        case 1: return GOLD_POLISH;
        case 2: return SYCEE_POLISH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PolishType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PolishType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PolishType>() {
            public PolishType findValueByNumber(int number) {
              return PolishType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineItem.getDescriptor().getEnumTypes().get(4);
    }

    private static final PolishType[] VALUES = values();

    public static PolishType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PolishType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.PolishType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MsgDefineItem.proto\022\023ProtoNetWorkMessa" +
      "ge*\246\001\n\010ItemType\022\020\n\014CONSUME_ITEM\020\001\022\016\n\nEQU" +
      "IP_ITEM\020\002\022\016\n\nCHEST_ITEM\020\003\022\014\n\010GEM_ITEM\020\004\022" +
      "\021\n\rCURRENCY_ITEM\020\005\022\021\n\rMATERIAL_ITEM\020\006\022\017\n" +
      "\013BUFFER_ITEM\020\007\022\023\n\017SKILL_BOOK_ITEM\020\010\022\016\n\nN" +
      "OMAL_ITEM\020\t*X\n\tItemColor\022\t\n\005WHITE\020\001\022\t\n\005G" +
      "REEN\020\002\022\010\n\004BLUE\020\003\022\n\n\006PURPLE\020\004\022\n\n\006GOLDEN\020\005" +
      "\022\n\n\006ORANGE\020\006\022\007\n\003RED\020\007*\322\001\n\013ReflectType\022\023\n" +
      "\017ADD_HP_ONE_TIME\020\001\022\025\n\021ADD_FURY_ONE_TIME\020" +
      "\002\022\027\n\023ADD_ENERGY_ONE_TIME\020\003\022\025\n\021ADD_GOLD_O",
      "NE_TIME\020\004\022\026\n\022ADD_SYCEE_ONE_TIME\020\005\022\032\n\026ADD" +
      "_GEM_PIECE_ONE_TIME\020\006\022\031\n\025ADD_ROLE_EXP_ON" +
      "E_TIME\020\007\022\030\n\024ADD_PET_EXP_ONE_TIME\020\010*t\n\004Pa" +
      "rt\022\017\n\013WEAPON_PART\020\001\022\020\n\014CLOTHES_PART\020\002\022\r\n" +
      "\tHAND_PART\020\003\022\017\n\013HELMET_PART\020\004\022\r\n\tBELT_PA" +
      "RT\020\005\022\r\n\tSHOE_PART\020\006\022\013\n\007FASHION\020\007*/\n\nPoli" +
      "shType\022\017\n\013GOLD_POLISH\020\001\022\020\n\014SYCEE_POLISH\020" +
      "\002B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
