// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgDefineMission.proto

package com.base.pb;

public final class MsgDefineMission {
  private MsgDefineMission() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ProtoNetWorkMessage.MissionType}
   *
   * <pre>
   *任务类型
   * </pre>
   */
  public enum MissionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MAIN_MISSION = 1;</code>
     *
     * <pre>
     *主线任务
     * </pre>
     */
    MAIN_MISSION(0, 1),
    /**
     * <code>SIDE_MISSION = 2;</code>
     *
     * <pre>
     *支线任务
     * </pre>
     */
    SIDE_MISSION(1, 2),
    /**
     * <code>ROUTINE_MISSION = 3;</code>
     *
     * <pre>
     *日常任务
     * </pre>
     */
    ROUTINE_MISSION(2, 3),
    ;

    /**
     * <code>MAIN_MISSION = 1;</code>
     *
     * <pre>
     *主线任务
     * </pre>
     */
    public static final int MAIN_MISSION_VALUE = 1;
    /**
     * <code>SIDE_MISSION = 2;</code>
     *
     * <pre>
     *支线任务
     * </pre>
     */
    public static final int SIDE_MISSION_VALUE = 2;
    /**
     * <code>ROUTINE_MISSION = 3;</code>
     *
     * <pre>
     *日常任务
     * </pre>
     */
    public static final int ROUTINE_MISSION_VALUE = 3;


    public final int getNumber() { return value; }

    public static MissionType valueOf(int value) {
      switch (value) {
        case 1: return MAIN_MISSION;
        case 2: return SIDE_MISSION;
        case 3: return ROUTINE_MISSION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MissionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MissionType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MissionType>() {
            public MissionType findValueByNumber(int number) {
              return MissionType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineMission.getDescriptor().getEnumTypes().get(0);
    }

    private static final MissionType[] VALUES = values();

    public static MissionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MissionType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.MissionType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.MissionTargetType}
   *
   * <pre>
   *任务目标类型
   * </pre>
   */
  public enum MissionTargetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DUNGEON_TARGET = 1;</code>
     *
     * <pre>
     *关卡目标
     * </pre>
     */
    DUNGEON_TARGET(0, 1),
    /**
     * <code>KILL_MONSTER_TARGET = 2;</code>
     *
     * <pre>
     *击杀怪物目标
     * </pre>
     */
    KILL_MONSTER_TARGET(1, 2),
    /**
     * <code>RUN_AWAY_TARGET = 3;</code>
     *
     * <pre>
     *跑路任务目标
     * </pre>
     */
    RUN_AWAY_TARGET(2, 3),
    /**
     * <code>ITEM_USE_TARGET = 4;</code>
     *
     * <pre>
     * 物品使用目标
     * </pre>
     */
    ITEM_USE_TARGET(3, 4),
    /**
     * <code>POLISH_TRAGET = 5;</code>
     *
     * <pre>
     *洗练次数目标
     * </pre>
     */
    POLISH_TRAGET(4, 5),
    /**
     * <code>STRENG_THEN_TARGET = 6;</code>
     *
     * <pre>
     *强化次数目标
     * </pre>
     */
    STRENG_THEN_TARGET(5, 6),
    /**
     * <code>EFFECT_UP_TARGET = 7;</code>
     *
     * <pre>
     *战斗力达到目标
     * </pre>
     */
    EFFECT_UP_TARGET(6, 7),
    /**
     * <code>GEM_INLAY_TARGET = 8;</code>
     *
     * <pre>
     *镶嵌宝石目标
     * </pre>
     */
    GEM_INLAY_TARGET(7, 8),
    /**
     * <code>LEVEL_UP_TARGET = 9;</code>
     *
     * <pre>
     *等级达到任务目标
     * </pre>
     */
    LEVEL_UP_TARGET(8, 9),
    /**
     * <code>POLISH_COLOR_TARGET = 10;</code>
     *
     * <pre>
     *洗练颜色任务目标
     * </pre>
     */
    POLISH_COLOR_TARGET(9, 10),
    ;

    /**
     * <code>DUNGEON_TARGET = 1;</code>
     *
     * <pre>
     *关卡目标
     * </pre>
     */
    public static final int DUNGEON_TARGET_VALUE = 1;
    /**
     * <code>KILL_MONSTER_TARGET = 2;</code>
     *
     * <pre>
     *击杀怪物目标
     * </pre>
     */
    public static final int KILL_MONSTER_TARGET_VALUE = 2;
    /**
     * <code>RUN_AWAY_TARGET = 3;</code>
     *
     * <pre>
     *跑路任务目标
     * </pre>
     */
    public static final int RUN_AWAY_TARGET_VALUE = 3;
    /**
     * <code>ITEM_USE_TARGET = 4;</code>
     *
     * <pre>
     * 物品使用目标
     * </pre>
     */
    public static final int ITEM_USE_TARGET_VALUE = 4;
    /**
     * <code>POLISH_TRAGET = 5;</code>
     *
     * <pre>
     *洗练次数目标
     * </pre>
     */
    public static final int POLISH_TRAGET_VALUE = 5;
    /**
     * <code>STRENG_THEN_TARGET = 6;</code>
     *
     * <pre>
     *强化次数目标
     * </pre>
     */
    public static final int STRENG_THEN_TARGET_VALUE = 6;
    /**
     * <code>EFFECT_UP_TARGET = 7;</code>
     *
     * <pre>
     *战斗力达到目标
     * </pre>
     */
    public static final int EFFECT_UP_TARGET_VALUE = 7;
    /**
     * <code>GEM_INLAY_TARGET = 8;</code>
     *
     * <pre>
     *镶嵌宝石目标
     * </pre>
     */
    public static final int GEM_INLAY_TARGET_VALUE = 8;
    /**
     * <code>LEVEL_UP_TARGET = 9;</code>
     *
     * <pre>
     *等级达到任务目标
     * </pre>
     */
    public static final int LEVEL_UP_TARGET_VALUE = 9;
    /**
     * <code>POLISH_COLOR_TARGET = 10;</code>
     *
     * <pre>
     *洗练颜色任务目标
     * </pre>
     */
    public static final int POLISH_COLOR_TARGET_VALUE = 10;


    public final int getNumber() { return value; }

    public static MissionTargetType valueOf(int value) {
      switch (value) {
        case 1: return DUNGEON_TARGET;
        case 2: return KILL_MONSTER_TARGET;
        case 3: return RUN_AWAY_TARGET;
        case 4: return ITEM_USE_TARGET;
        case 5: return POLISH_TRAGET;
        case 6: return STRENG_THEN_TARGET;
        case 7: return EFFECT_UP_TARGET;
        case 8: return GEM_INLAY_TARGET;
        case 9: return LEVEL_UP_TARGET;
        case 10: return POLISH_COLOR_TARGET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MissionTargetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MissionTargetType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MissionTargetType>() {
            public MissionTargetType findValueByNumber(int number) {
              return MissionTargetType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineMission.getDescriptor().getEnumTypes().get(1);
    }

    private static final MissionTargetType[] VALUES = values();

    public static MissionTargetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MissionTargetType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.MissionTargetType)
  }

  /**
   * Protobuf enum {@code ProtoNetWorkMessage.MissionStatus}
   *
   * <pre>
   *任务状态
   * </pre>
   */
  public enum MissionStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MISSION_ON_GOING = 1;</code>
     *
     * <pre>
     *任务正在进行中
     * </pre>
     */
    MISSION_ON_GOING(0, 1),
    /**
     * <code>MISSION_PERFORMED = 2;</code>
     *
     * <pre>
     *任务完成(可以领取奖励)
     * </pre>
     */
    MISSION_PERFORMED(1, 2),
    /**
     * <code>MISSION_FINISH = 3;</code>
     *
     * <pre>
     *任务完成
     * </pre>
     */
    MISSION_FINISH(2, 3),
    /**
     * <code>MISSION_CAN_GET = 4;</code>
     *
     * <pre>
     *任务可接
     * </pre>
     */
    MISSION_CAN_GET(3, 4),
    /**
     * <code>MISSION_CAN_NOT_GET = 5;</code>
     *
     * <pre>
     *任务不可领取
     * </pre>
     */
    MISSION_CAN_NOT_GET(4, 5),
    ;

    /**
     * <code>MISSION_ON_GOING = 1;</code>
     *
     * <pre>
     *任务正在进行中
     * </pre>
     */
    public static final int MISSION_ON_GOING_VALUE = 1;
    /**
     * <code>MISSION_PERFORMED = 2;</code>
     *
     * <pre>
     *任务完成(可以领取奖励)
     * </pre>
     */
    public static final int MISSION_PERFORMED_VALUE = 2;
    /**
     * <code>MISSION_FINISH = 3;</code>
     *
     * <pre>
     *任务完成
     * </pre>
     */
    public static final int MISSION_FINISH_VALUE = 3;
    /**
     * <code>MISSION_CAN_GET = 4;</code>
     *
     * <pre>
     *任务可接
     * </pre>
     */
    public static final int MISSION_CAN_GET_VALUE = 4;
    /**
     * <code>MISSION_CAN_NOT_GET = 5;</code>
     *
     * <pre>
     *任务不可领取
     * </pre>
     */
    public static final int MISSION_CAN_NOT_GET_VALUE = 5;


    public final int getNumber() { return value; }

    public static MissionStatus valueOf(int value) {
      switch (value) {
        case 1: return MISSION_ON_GOING;
        case 2: return MISSION_PERFORMED;
        case 3: return MISSION_FINISH;
        case 4: return MISSION_CAN_GET;
        case 5: return MISSION_CAN_NOT_GET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MissionStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MissionStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MissionStatus>() {
            public MissionStatus findValueByNumber(int number) {
              return MissionStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.base.pb.MsgDefineMission.getDescriptor().getEnumTypes().get(2);
    }

    private static final MissionStatus[] VALUES = values();

    public static MissionStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MissionStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ProtoNetWorkMessage.MissionStatus)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MsgDefineMission.proto\022\023ProtoNetWorkMe" +
      "ssage*F\n\013MissionType\022\020\n\014MAIN_MISSION\020\001\022\020" +
      "\n\014SIDE_MISSION\020\002\022\023\n\017ROUTINE_MISSION\020\003*\357\001" +
      "\n\021MissionTargetType\022\022\n\016DUNGEON_TARGET\020\001\022" +
      "\027\n\023KILL_MONSTER_TARGET\020\002\022\023\n\017RUN_AWAY_TAR" +
      "GET\020\003\022\023\n\017ITEM_USE_TARGET\020\004\022\021\n\rPOLISH_TRA" +
      "GET\020\005\022\026\n\022STRENG_THEN_TARGET\020\006\022\024\n\020EFFECT_" +
      "UP_TARGET\020\007\022\024\n\020GEM_INLAY_TARGET\020\010\022\023\n\017LEV" +
      "EL_UP_TARGET\020\t\022\027\n\023POLISH_COLOR_TARGET\020\n*" +
      "~\n\rMissionStatus\022\024\n\020MISSION_ON_GOING\020\001\022\025",
      "\n\021MISSION_PERFORMED\020\002\022\022\n\016MISSION_FINISH\020" +
      "\003\022\023\n\017MISSION_CAN_GET\020\004\022\027\n\023MISSION_CAN_NO" +
      "T_GET\020\005B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
