// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRole.proto

package com.base.pb;

public final class MsgRole {
  private MsgRole() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResLevelChangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 level = 1;
    /**
     * <code>required int32 level = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResLevelChange}
   *
   * <pre>
   *RES_ROLE_LEVEL_CHANGE = 10500;//角色等级变化
   * </pre>
   */
  public static final class ResLevelChange extends
      com.google.protobuf.GeneratedMessage
      implements ResLevelChangeOrBuilder {
    // Use ResLevelChange.newBuilder() to construct.
    private ResLevelChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResLevelChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResLevelChange defaultInstance;
    public static ResLevelChange getDefaultInstance() {
      return defaultInstance;
    }

    public ResLevelChange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResLevelChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResLevelChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgRole.ResLevelChange.class, com.base.pb.MsgRole.ResLevelChange.Builder.class);
    }

    public static com.google.protobuf.Parser<ResLevelChange> PARSER =
        new com.google.protobuf.AbstractParser<ResLevelChange>() {
      public ResLevelChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResLevelChange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResLevelChange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 level = 1;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>required int32 level = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 level = 1;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    private void initFields() {
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, level_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResLevelChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgRole.ResLevelChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResLevelChange}
     *
     * <pre>
     *RES_ROLE_LEVEL_CHANGE = 10500;//角色等级变化
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgRole.ResLevelChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResLevelChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgRole.ResLevelChange.class, com.base.pb.MsgRole.ResLevelChange.Builder.class);
      }

      // Construct using com.base.pb.MsgRole.ResLevelChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor;
      }

      public com.base.pb.MsgRole.ResLevelChange getDefaultInstanceForType() {
        return com.base.pb.MsgRole.ResLevelChange.getDefaultInstance();
      }

      public com.base.pb.MsgRole.ResLevelChange build() {
        com.base.pb.MsgRole.ResLevelChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgRole.ResLevelChange buildPartial() {
        com.base.pb.MsgRole.ResLevelChange result = new com.base.pb.MsgRole.ResLevelChange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgRole.ResLevelChange) {
          return mergeFrom((com.base.pb.MsgRole.ResLevelChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgRole.ResLevelChange other) {
        if (other == com.base.pb.MsgRole.ResLevelChange.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgRole.ResLevelChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgRole.ResLevelChange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 level = 1;
      private int level_ ;
      /**
       * <code>required int32 level = 1;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 level = 1;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 1;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 1;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResLevelChange)
    }

    static {
      defaultInstance = new ResLevelChange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResLevelChange)
  }

  public interface ResExpChangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 exp = 1;
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    boolean hasExp();
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    long getExp();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResExpChange}
   *
   * <pre>
   *RES_ROLE_EXP_CHANGE = 10501;//角色经验变化
   * </pre>
   */
  public static final class ResExpChange extends
      com.google.protobuf.GeneratedMessage
      implements ResExpChangeOrBuilder {
    // Use ResExpChange.newBuilder() to construct.
    private ResExpChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResExpChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResExpChange defaultInstance;
    public static ResExpChange getDefaultInstance() {
      return defaultInstance;
    }

    public ResExpChange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResExpChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              exp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResExpChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResExpChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgRole.ResExpChange.class, com.base.pb.MsgRole.ResExpChange.Builder.class);
    }

    public static com.google.protobuf.Parser<ResExpChange> PARSER =
        new com.google.protobuf.AbstractParser<ResExpChange>() {
      public ResExpChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResExpChange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResExpChange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 exp = 1;
    public static final int EXP_FIELD_NUMBER = 1;
    private long exp_;
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 exp = 1;</code>
     *
     * <pre>
     *经验
     * </pre>
     */
    public long getExp() {
      return exp_;
    }

    private void initFields() {
      exp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, exp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, exp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResExpChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgRole.ResExpChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResExpChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgRole.ResExpChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResExpChange}
     *
     * <pre>
     *RES_ROLE_EXP_CHANGE = 10501;//角色经验变化
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgRole.ResExpChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResExpChange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResExpChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgRole.ResExpChange.class, com.base.pb.MsgRole.ResExpChange.Builder.class);
      }

      // Construct using com.base.pb.MsgRole.ResExpChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        exp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResExpChange_descriptor;
      }

      public com.base.pb.MsgRole.ResExpChange getDefaultInstanceForType() {
        return com.base.pb.MsgRole.ResExpChange.getDefaultInstance();
      }

      public com.base.pb.MsgRole.ResExpChange build() {
        com.base.pb.MsgRole.ResExpChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgRole.ResExpChange buildPartial() {
        com.base.pb.MsgRole.ResExpChange result = new com.base.pb.MsgRole.ResExpChange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.exp_ = exp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgRole.ResExpChange) {
          return mergeFrom((com.base.pb.MsgRole.ResExpChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgRole.ResExpChange other) {
        if (other == com.base.pb.MsgRole.ResExpChange.getDefaultInstance()) return this;
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasExp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgRole.ResExpChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgRole.ResExpChange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 exp = 1;
      private long exp_ ;
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *经验
       * </pre>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *经验
       * </pre>
       */
      public long getExp() {
        return exp_;
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *经验
       * </pre>
       */
      public Builder setExp(long value) {
        bitField0_ |= 0x00000001;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 exp = 1;</code>
       *
       * <pre>
       *经验
       * </pre>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        exp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResExpChange)
    }

    static {
      defaultInstance = new ResExpChange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResExpChange)
  }

  public interface ResCurrencyChangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 currencyType = 1;
    /**
     * <code>required int32 currencyType = 1;</code>
     *
     * <pre>
     *货币改变类型
     * </pre>
     */
    boolean hasCurrencyType();
    /**
     * <code>required int32 currencyType = 1;</code>
     *
     * <pre>
     *货币改变类型
     * </pre>
     */
    int getCurrencyType();

    // required int32 currency = 2;
    /**
     * <code>required int32 currency = 2;</code>
     *
     * <pre>
     *货币数量
     * </pre>
     */
    boolean hasCurrency();
    /**
     * <code>required int32 currency = 2;</code>
     *
     * <pre>
     *货币数量
     * </pre>
     */
    int getCurrency();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResCurrencyChange}
   *
   * <pre>
   *RES_ROLE_CURRENCY_CHANGE = 10502;//角色货币变化
   * </pre>
   */
  public static final class ResCurrencyChange extends
      com.google.protobuf.GeneratedMessage
      implements ResCurrencyChangeOrBuilder {
    // Use ResCurrencyChange.newBuilder() to construct.
    private ResCurrencyChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResCurrencyChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResCurrencyChange defaultInstance;
    public static ResCurrencyChange getDefaultInstance() {
      return defaultInstance;
    }

    public ResCurrencyChange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResCurrencyChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currencyType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currency_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResCurrencyChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgRole.ResCurrencyChange.class, com.base.pb.MsgRole.ResCurrencyChange.Builder.class);
    }

    public static com.google.protobuf.Parser<ResCurrencyChange> PARSER =
        new com.google.protobuf.AbstractParser<ResCurrencyChange>() {
      public ResCurrencyChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResCurrencyChange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResCurrencyChange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 currencyType = 1;
    public static final int CURRENCYTYPE_FIELD_NUMBER = 1;
    private int currencyType_;
    /**
     * <code>required int32 currencyType = 1;</code>
     *
     * <pre>
     *货币改变类型
     * </pre>
     */
    public boolean hasCurrencyType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 currencyType = 1;</code>
     *
     * <pre>
     *货币改变类型
     * </pre>
     */
    public int getCurrencyType() {
      return currencyType_;
    }

    // required int32 currency = 2;
    public static final int CURRENCY_FIELD_NUMBER = 2;
    private int currency_;
    /**
     * <code>required int32 currency = 2;</code>
     *
     * <pre>
     *货币数量
     * </pre>
     */
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 currency = 2;</code>
     *
     * <pre>
     *货币数量
     * </pre>
     */
    public int getCurrency() {
      return currency_;
    }

    private void initFields() {
      currencyType_ = 0;
      currency_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCurrencyType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, currencyType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currency_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, currencyType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currency_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResCurrencyChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgRole.ResCurrencyChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResCurrencyChange}
     *
     * <pre>
     *RES_ROLE_CURRENCY_CHANGE = 10502;//角色货币变化
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgRole.ResCurrencyChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResCurrencyChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgRole.ResCurrencyChange.class, com.base.pb.MsgRole.ResCurrencyChange.Builder.class);
      }

      // Construct using com.base.pb.MsgRole.ResCurrencyChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        currencyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currency_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor;
      }

      public com.base.pb.MsgRole.ResCurrencyChange getDefaultInstanceForType() {
        return com.base.pb.MsgRole.ResCurrencyChange.getDefaultInstance();
      }

      public com.base.pb.MsgRole.ResCurrencyChange build() {
        com.base.pb.MsgRole.ResCurrencyChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgRole.ResCurrencyChange buildPartial() {
        com.base.pb.MsgRole.ResCurrencyChange result = new com.base.pb.MsgRole.ResCurrencyChange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currencyType_ = currencyType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currency_ = currency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgRole.ResCurrencyChange) {
          return mergeFrom((com.base.pb.MsgRole.ResCurrencyChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgRole.ResCurrencyChange other) {
        if (other == com.base.pb.MsgRole.ResCurrencyChange.getDefaultInstance()) return this;
        if (other.hasCurrencyType()) {
          setCurrencyType(other.getCurrencyType());
        }
        if (other.hasCurrency()) {
          setCurrency(other.getCurrency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrencyType()) {
          
          return false;
        }
        if (!hasCurrency()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgRole.ResCurrencyChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgRole.ResCurrencyChange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 currencyType = 1;
      private int currencyType_ ;
      /**
       * <code>required int32 currencyType = 1;</code>
       *
       * <pre>
       *货币改变类型
       * </pre>
       */
      public boolean hasCurrencyType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 currencyType = 1;</code>
       *
       * <pre>
       *货币改变类型
       * </pre>
       */
      public int getCurrencyType() {
        return currencyType_;
      }
      /**
       * <code>required int32 currencyType = 1;</code>
       *
       * <pre>
       *货币改变类型
       * </pre>
       */
      public Builder setCurrencyType(int value) {
        bitField0_ |= 0x00000001;
        currencyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currencyType = 1;</code>
       *
       * <pre>
       *货币改变类型
       * </pre>
       */
      public Builder clearCurrencyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currencyType_ = 0;
        onChanged();
        return this;
      }

      // required int32 currency = 2;
      private int currency_ ;
      /**
       * <code>required int32 currency = 2;</code>
       *
       * <pre>
       *货币数量
       * </pre>
       */
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 currency = 2;</code>
       *
       * <pre>
       *货币数量
       * </pre>
       */
      public int getCurrency() {
        return currency_;
      }
      /**
       * <code>required int32 currency = 2;</code>
       *
       * <pre>
       *货币数量
       * </pre>
       */
      public Builder setCurrency(int value) {
        bitField0_ |= 0x00000002;
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currency = 2;</code>
       *
       * <pre>
       *货币数量
       * </pre>
       */
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currency_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResCurrencyChange)
    }

    static {
      defaultInstance = new ResCurrencyChange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResCurrencyChange)
  }

  public interface ReqRoleEnergyAddingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ReqRoleEnergyAdding}
   *
   * <pre>
   *REQ_ROLE_ENERGY_ADDING = 100503;//请求增加体力
   * </pre>
   */
  public static final class ReqRoleEnergyAdding extends
      com.google.protobuf.GeneratedMessage
      implements ReqRoleEnergyAddingOrBuilder {
    // Use ReqRoleEnergyAdding.newBuilder() to construct.
    private ReqRoleEnergyAdding(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqRoleEnergyAdding(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqRoleEnergyAdding defaultInstance;
    public static ReqRoleEnergyAdding getDefaultInstance() {
      return defaultInstance;
    }

    public ReqRoleEnergyAdding getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRoleEnergyAdding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgRole.ReqRoleEnergyAdding.class, com.base.pb.MsgRole.ReqRoleEnergyAdding.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqRoleEnergyAdding> PARSER =
        new com.google.protobuf.AbstractParser<ReqRoleEnergyAdding>() {
      public ReqRoleEnergyAdding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqRoleEnergyAdding(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRoleEnergyAdding> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ReqRoleEnergyAdding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgRole.ReqRoleEnergyAdding prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ReqRoleEnergyAdding}
     *
     * <pre>
     *REQ_ROLE_ENERGY_ADDING = 100503;//请求增加体力
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgRole.ReqRoleEnergyAddingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgRole.ReqRoleEnergyAdding.class, com.base.pb.MsgRole.ReqRoleEnergyAdding.Builder.class);
      }

      // Construct using com.base.pb.MsgRole.ReqRoleEnergyAdding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor;
      }

      public com.base.pb.MsgRole.ReqRoleEnergyAdding getDefaultInstanceForType() {
        return com.base.pb.MsgRole.ReqRoleEnergyAdding.getDefaultInstance();
      }

      public com.base.pb.MsgRole.ReqRoleEnergyAdding build() {
        com.base.pb.MsgRole.ReqRoleEnergyAdding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgRole.ReqRoleEnergyAdding buildPartial() {
        com.base.pb.MsgRole.ReqRoleEnergyAdding result = new com.base.pb.MsgRole.ReqRoleEnergyAdding(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgRole.ReqRoleEnergyAdding) {
          return mergeFrom((com.base.pb.MsgRole.ReqRoleEnergyAdding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgRole.ReqRoleEnergyAdding other) {
        if (other == com.base.pb.MsgRole.ReqRoleEnergyAdding.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgRole.ReqRoleEnergyAdding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgRole.ReqRoleEnergyAdding) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ReqRoleEnergyAdding)
    }

    static {
      defaultInstance = new ReqRoleEnergyAdding(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ReqRoleEnergyAdding)
  }

  public interface ResRoleEnergyAddingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 time = 1;
    /**
     * <code>required int32 time = 1;</code>
     *
     * <pre>
     *体力增加倒计时(毫秒)
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required int32 time = 1;</code>
     *
     * <pre>
     *体力增加倒计时(毫秒)
     * </pre>
     */
    int getTime();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResRoleEnergyAdding}
   *
   * <pre>
   *RES_ROLE_ENERGY_ADDING = 100504;//增加体力返回
   * </pre>
   */
  public static final class ResRoleEnergyAdding extends
      com.google.protobuf.GeneratedMessage
      implements ResRoleEnergyAddingOrBuilder {
    // Use ResRoleEnergyAdding.newBuilder() to construct.
    private ResRoleEnergyAdding(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResRoleEnergyAdding(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResRoleEnergyAdding defaultInstance;
    public static ResRoleEnergyAdding getDefaultInstance() {
      return defaultInstance;
    }

    public ResRoleEnergyAdding getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResRoleEnergyAdding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgRole.ResRoleEnergyAdding.class, com.base.pb.MsgRole.ResRoleEnergyAdding.Builder.class);
    }

    public static com.google.protobuf.Parser<ResRoleEnergyAdding> PARSER =
        new com.google.protobuf.AbstractParser<ResRoleEnergyAdding>() {
      public ResRoleEnergyAdding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResRoleEnergyAdding(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResRoleEnergyAdding> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private int time_;
    /**
     * <code>required int32 time = 1;</code>
     *
     * <pre>
     *体力增加倒计时(毫秒)
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 time = 1;</code>
     *
     * <pre>
     *体力增加倒计时(毫秒)
     * </pre>
     */
    public int getTime() {
      return time_;
    }

    private void initFields() {
      time_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgRole.ResRoleEnergyAdding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgRole.ResRoleEnergyAdding prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResRoleEnergyAdding}
     *
     * <pre>
     *RES_ROLE_ENERGY_ADDING = 100504;//增加体力返回
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgRole.ResRoleEnergyAddingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgRole.ResRoleEnergyAdding.class, com.base.pb.MsgRole.ResRoleEnergyAdding.Builder.class);
      }

      // Construct using com.base.pb.MsgRole.ResRoleEnergyAdding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgRole.internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor;
      }

      public com.base.pb.MsgRole.ResRoleEnergyAdding getDefaultInstanceForType() {
        return com.base.pb.MsgRole.ResRoleEnergyAdding.getDefaultInstance();
      }

      public com.base.pb.MsgRole.ResRoleEnergyAdding build() {
        com.base.pb.MsgRole.ResRoleEnergyAdding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgRole.ResRoleEnergyAdding buildPartial() {
        com.base.pb.MsgRole.ResRoleEnergyAdding result = new com.base.pb.MsgRole.ResRoleEnergyAdding(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgRole.ResRoleEnergyAdding) {
          return mergeFrom((com.base.pb.MsgRole.ResRoleEnergyAdding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgRole.ResRoleEnergyAdding other) {
        if (other == com.base.pb.MsgRole.ResRoleEnergyAdding.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgRole.ResRoleEnergyAdding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgRole.ResRoleEnergyAdding) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 time = 1;
      private int time_ ;
      /**
       * <code>required int32 time = 1;</code>
       *
       * <pre>
       *体力增加倒计时(毫秒)
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 time = 1;</code>
       *
       * <pre>
       *体力增加倒计时(毫秒)
       * </pre>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>required int32 time = 1;</code>
       *
       * <pre>
       *体力增加倒计时(毫秒)
       * </pre>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 time = 1;</code>
       *
       * <pre>
       *体力增加倒计时(毫秒)
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResRoleEnergyAdding)
    }

    static {
      defaultInstance = new ResRoleEnergyAdding(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResRoleEnergyAdding)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResLevelChange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResExpChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResExpChange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResCurrencyChange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgRole.proto\022\023ProtoNetWorkMessage\"\037\n\016" +
      "ResLevelChange\022\r\n\005level\030\001 \002(\005\"\033\n\014ResExpC" +
      "hange\022\013\n\003exp\030\001 \002(\003\";\n\021ResCurrencyChange\022" +
      "\024\n\014currencyType\030\001 \002(\005\022\020\n\010currency\030\002 \002(\005\"" +
      "\025\n\023ReqRoleEnergyAdding\"#\n\023ResRoleEnergyA" +
      "dding\022\014\n\004time\030\001 \002(\005B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoNetWorkMessage_ResLevelChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResLevelChange_descriptor,
              new java.lang.String[] { "Level", });
          internal_static_ProtoNetWorkMessage_ResExpChange_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtoNetWorkMessage_ResExpChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResExpChange_descriptor,
              new java.lang.String[] { "Exp", });
          internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ProtoNetWorkMessage_ResCurrencyChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResCurrencyChange_descriptor,
              new java.lang.String[] { "CurrencyType", "Currency", });
          internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ReqRoleEnergyAdding_descriptor,
              new java.lang.String[] { });
          internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResRoleEnergyAdding_descriptor,
              new java.lang.String[] { "Time", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
