// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgSystem.proto

package com.base.pb;

public final class MsgSystem {
  private MsgSystem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResAlertOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    int getType();

    // repeated string parameter = 2;
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    java.util.List<java.lang.String>
    getParameterList();
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    int getParameterCount();
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    java.lang.String getParameter(int index);
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    com.google.protobuf.ByteString
        getParameterBytes(int index);
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResAlert}
   *
   * <pre>
   *RES_ALERT = 9000;//提示信息
   * </pre>
   */
  public static final class ResAlert extends
      com.google.protobuf.GeneratedMessage
      implements ResAlertOrBuilder {
    // Use ResAlert.newBuilder() to construct.
    private ResAlert(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResAlert(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResAlert defaultInstance;
    public static ResAlert getDefaultInstance() {
      return defaultInstance;
    }

    public ResAlert getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResAlert(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                parameter_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              parameter_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          parameter_ = new com.google.protobuf.UnmodifiableLazyStringList(parameter_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResAlert_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResAlert_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgSystem.ResAlert.class, com.base.pb.MsgSystem.ResAlert.Builder.class);
    }

    public static com.google.protobuf.Parser<ResAlert> PARSER =
        new com.google.protobuf.AbstractParser<ResAlert>() {
      public ResAlert parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResAlert(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResAlert> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *错误类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // repeated string parameter = 2;
    public static final int PARAMETER_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList parameter_;
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    public java.util.List<java.lang.String>
        getParameterList() {
      return parameter_;
    }
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    public int getParameterCount() {
      return parameter_.size();
    }
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    public java.lang.String getParameter(int index) {
      return parameter_.get(index);
    }
    /**
     * <code>repeated string parameter = 2;</code>
     *
     * <pre>
     *参数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getParameterBytes(int index) {
      return parameter_.getByteString(index);
    }

    private void initFields() {
      type_ = 0;
      parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      for (int i = 0; i < parameter_.size(); i++) {
        output.writeBytes(2, parameter_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameter_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameter_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParameterList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResAlert parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgSystem.ResAlert parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ResAlert parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgSystem.ResAlert prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResAlert}
     *
     * <pre>
     *RES_ALERT = 9000;//提示信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgSystem.ResAlertOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResAlert_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResAlert_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgSystem.ResAlert.class, com.base.pb.MsgSystem.ResAlert.Builder.class);
      }

      // Construct using com.base.pb.MsgSystem.ResAlert.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResAlert_descriptor;
      }

      public com.base.pb.MsgSystem.ResAlert getDefaultInstanceForType() {
        return com.base.pb.MsgSystem.ResAlert.getDefaultInstance();
      }

      public com.base.pb.MsgSystem.ResAlert build() {
        com.base.pb.MsgSystem.ResAlert result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgSystem.ResAlert buildPartial() {
        com.base.pb.MsgSystem.ResAlert result = new com.base.pb.MsgSystem.ResAlert(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          parameter_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parameter_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.parameter_ = parameter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgSystem.ResAlert) {
          return mergeFrom((com.base.pb.MsgSystem.ResAlert)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgSystem.ResAlert other) {
        if (other == com.base.pb.MsgSystem.ResAlert.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.parameter_.isEmpty()) {
          if (parameter_.isEmpty()) {
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParameterIsMutable();
            parameter_.addAll(other.parameter_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgSystem.ResAlert parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgSystem.ResAlert) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *错误类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // repeated string parameter = 2;
      private com.google.protobuf.LazyStringList parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParameterIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          parameter_ = new com.google.protobuf.LazyStringArrayList(parameter_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public java.util.List<java.lang.String>
          getParameterList() {
        return java.util.Collections.unmodifiableList(parameter_);
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public int getParameterCount() {
        return parameter_.size();
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public java.lang.String getParameter(int index) {
        return parameter_.get(index);
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getParameterBytes(int index) {
        return parameter_.getByteString(index);
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public Builder setParameter(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public Builder addParameter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public Builder addAllParameter(
          java.lang.Iterable<java.lang.String> values) {
        ensureParameterIsMutable();
        super.addAll(values, parameter_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public Builder clearParameter() {
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parameter = 2;</code>
       *
       * <pre>
       *参数
       * </pre>
       */
      public Builder addParameterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResAlert)
    }

    static {
      defaultInstance = new ResAlert(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResAlert)
  }

  public interface ReqHeartbeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 time = 1;
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前客户端系统时间
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前客户端系统时间
     * </pre>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ReqHeartbeat}
   *
   * <pre>
   *REQ_HEARTBEAT = 9001;//心跳包（客户端上传本地时间）
   * </pre>
   */
  public static final class ReqHeartbeat extends
      com.google.protobuf.GeneratedMessage
      implements ReqHeartbeatOrBuilder {
    // Use ReqHeartbeat.newBuilder() to construct.
    private ReqHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqHeartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqHeartbeat defaultInstance;
    public static ReqHeartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public ReqHeartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqHeartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ReqHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgSystem.ReqHeartbeat.class, com.base.pb.MsgSystem.ReqHeartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqHeartbeat> PARSER =
        new com.google.protobuf.AbstractParser<ReqHeartbeat>() {
      public ReqHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqHeartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHeartbeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前客户端系统时间
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前客户端系统时间
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    private void initFields() {
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ReqHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgSystem.ReqHeartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ReqHeartbeat}
     *
     * <pre>
     *REQ_HEARTBEAT = 9001;//心跳包（客户端上传本地时间）
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgSystem.ReqHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ReqHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgSystem.ReqHeartbeat.class, com.base.pb.MsgSystem.ReqHeartbeat.Builder.class);
      }

      // Construct using com.base.pb.MsgSystem.ReqHeartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor;
      }

      public com.base.pb.MsgSystem.ReqHeartbeat getDefaultInstanceForType() {
        return com.base.pb.MsgSystem.ReqHeartbeat.getDefaultInstance();
      }

      public com.base.pb.MsgSystem.ReqHeartbeat build() {
        com.base.pb.MsgSystem.ReqHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgSystem.ReqHeartbeat buildPartial() {
        com.base.pb.MsgSystem.ReqHeartbeat result = new com.base.pb.MsgSystem.ReqHeartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgSystem.ReqHeartbeat) {
          return mergeFrom((com.base.pb.MsgSystem.ReqHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgSystem.ReqHeartbeat other) {
        if (other == com.base.pb.MsgSystem.ReqHeartbeat.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgSystem.ReqHeartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgSystem.ReqHeartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 time = 1;
      private long time_ ;
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前客户端系统时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前客户端系统时间
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前客户端系统时间
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前客户端系统时间
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ReqHeartbeat)
    }

    static {
      defaultInstance = new ReqHeartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ReqHeartbeat)
  }

  public interface ResHeartbeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 time = 1;
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前服务器系统时间
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前服务器系统时间
     * </pre>
     */
    long getTime();
  }
  /**
   * Protobuf type {@code ProtoNetWorkMessage.ResHeartbeat}
   *
   * <pre>
   *RES_HEARTBEAT = 9002;//服务器返回系统时间
   * </pre>
   */
  public static final class ResHeartbeat extends
      com.google.protobuf.GeneratedMessage
      implements ResHeartbeatOrBuilder {
    // Use ResHeartbeat.newBuilder() to construct.
    private ResHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResHeartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResHeartbeat defaultInstance;
    public static ResHeartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public ResHeartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResHeartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.base.pb.MsgSystem.ResHeartbeat.class, com.base.pb.MsgSystem.ResHeartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<ResHeartbeat> PARSER =
        new com.google.protobuf.AbstractParser<ResHeartbeat>() {
      public ResHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResHeartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResHeartbeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 time = 1;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前服务器系统时间
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 time = 1;</code>
     *
     * <pre>
     *当前服务器系统时间
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    private void initFields() {
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, time_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.base.pb.MsgSystem.ResHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.base.pb.MsgSystem.ResHeartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoNetWorkMessage.ResHeartbeat}
     *
     * <pre>
     *RES_HEARTBEAT = 9002;//服务器返回系统时间
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.base.pb.MsgSystem.ResHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.base.pb.MsgSystem.ResHeartbeat.class, com.base.pb.MsgSystem.ResHeartbeat.Builder.class);
      }

      // Construct using com.base.pb.MsgSystem.ResHeartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.base.pb.MsgSystem.internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor;
      }

      public com.base.pb.MsgSystem.ResHeartbeat getDefaultInstanceForType() {
        return com.base.pb.MsgSystem.ResHeartbeat.getDefaultInstance();
      }

      public com.base.pb.MsgSystem.ResHeartbeat build() {
        com.base.pb.MsgSystem.ResHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.base.pb.MsgSystem.ResHeartbeat buildPartial() {
        com.base.pb.MsgSystem.ResHeartbeat result = new com.base.pb.MsgSystem.ResHeartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.base.pb.MsgSystem.ResHeartbeat) {
          return mergeFrom((com.base.pb.MsgSystem.ResHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.base.pb.MsgSystem.ResHeartbeat other) {
        if (other == com.base.pb.MsgSystem.ResHeartbeat.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.base.pb.MsgSystem.ResHeartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.base.pb.MsgSystem.ResHeartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 time = 1;
      private long time_ ;
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前服务器系统时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前服务器系统时间
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前服务器系统时间
       * </pre>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 1;</code>
       *
       * <pre>
       *当前服务器系统时间
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ProtoNetWorkMessage.ResHeartbeat)
    }

    static {
      defaultInstance = new ResHeartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ProtoNetWorkMessage.ResHeartbeat)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResAlert_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResAlert_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ReqHeartbeat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoNetWorkMessage_ResHeartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MsgSystem.proto\022\023ProtoNetWorkMessage\"+" +
      "\n\010ResAlert\022\014\n\004type\030\001 \002(\005\022\021\n\tparameter\030\002 " +
      "\003(\t\"\034\n\014ReqHeartbeat\022\014\n\004time\030\001 \002(\003\"\034\n\014Res" +
      "Heartbeat\022\014\n\004time\030\001 \002(\003B\r\n\013com.base.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoNetWorkMessage_ResAlert_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoNetWorkMessage_ResAlert_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResAlert_descriptor,
              new java.lang.String[] { "Type", "Parameter", });
          internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ProtoNetWorkMessage_ReqHeartbeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ReqHeartbeat_descriptor,
              new java.lang.String[] { "Time", });
          internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ProtoNetWorkMessage_ResHeartbeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoNetWorkMessage_ResHeartbeat_descriptor,
              new java.lang.String[] { "Time", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
